#!/usr/bin/env python3
"""
Script to create a proper TABERTA Results Dashboard notebook
"""
import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🧪 TABERTA Embedding Pipeline - Results Dashboard\n",
                "\n",
                "**Monitoring and efficiency metrics for TABERTA embedding experiments**\n",
                "\n",
                "This notebook displays:\n",
                "- ✅ Qdrant collections status (all datasets × models)\n",
                "- 📊 Efficiency metrics (throughput, storage, timing)\n",
                "- 📈 Model comparison and performance benchmarks\n",
                "- 🔍 Detailed metrics from all experiments\n",
                "\n",
                "---\n",
                "\n",
                "**Purpose:** Support reviewer comments on efficiency calculations  \n",
                "**Expected:** 6 datasets × 9 models = 54 total collections\n",
                "\n",
                "**⚙️ Environment Setup:** All packages installed ✅  \n",
                "**Run all cells to refresh:** Click ▶▶ or `Kernel → Restart & Run All`"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🔧 Environment Check\n",
                "\n",
                "**Required packages already installed:**\n",
                "- ✅ Python 3.10.12\n",
                "- ✅ matplotlib 3.10.8\n",
                "- ✅ seaborn 0.13.2\n",
                "- ✅ pandas 2.3.3\n",
                "- ✅ qdrant-client\n",
                "- ✅ numpy\n",
                "\n",
                "**Ready to run! Just execute all cells below.**"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 1️⃣ Setup & Imports"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import json\n",
                "import os\n",
                "import glob\n",
                "from pathlib import Path\n",
                "import pandas as pd\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "from datetime import datetime\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "# Qdrant\n",
                "try:\n",
                "    from qdrant_client import QdrantClient\n",
                "    qdrant = QdrantClient(host='localhost', port=6333)\n",
                "    print('✅ Connected to Qdrant')\n",
                "except Exception as e:\n",
                "    print(f'❌ Failed to connect to Qdrant: {e}')\n",
                "    qdrant = None\n",
                "\n",
                "# Display config\n",
                "pd.set_option('display.max_columns', None)\n",
                "pd.set_option('display.width', None)\n",
                "pd.set_option('display.max_colwidth', None)\n",
                "sns.set_style('whitegrid')\n",
                "plt.rcParams['figure.figsize'] = (14, 6)\n",
                "\n",
                "# Configuration\n",
                "DATASETS = ['wikidbs-10k', 'spider', 'bird', 'fetaqa', 'ottqa', 'tabfact']\n",
                "MODELS = ['supervised_v1', 'supervised_v2', 'supervised_v3', 'supervised_v4', 'supervised_v5',\n",
                "          'unsupervised_v6', 'hybrid_v7', 'baseline_sbert', 'baseline_mpnet']\n",
                "\n",
                "print(f'📊 Expected: {len(DATASETS)} datasets × {len(MODELS)} models = {len(DATASETS) * len(MODELS)} collections')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 2️⃣ Qdrant Collections Summary"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def get_all_collections():\n",
                "    '''Get all collections from Qdrant with details'''\n",
                "    if not qdrant:\n",
                "        return pd.DataFrame()\n",
                "    \n",
                "    collections = qdrant.get_collections().collections\n",
                "    data = []\n",
                "    \n",
                "    for col in collections:\n",
                "        try:\n",
                "            info = qdrant.get_collection(col.name)\n",
                "            \n",
                "            # Parse dataset and model\n",
                "            parts = col.name.split('_')\n",
                "            if 'test' in col.name.lower():\n",
                "                dataset = 'test'\n",
                "                model = col.name\n",
                "            else:\n",
                "                dataset = parts[0] if len(parts) > 0 else 'unknown'\n",
                "                model = '_'.join(parts[1:]) if len(parts) > 1 else 'unknown'\n",
                "            \n",
                "            data.append({\n",
                "                'Collection': col.name,\n",
                "                'Dataset': dataset,\n",
                "                'Model': model,\n",
                "                'Embeddings': info.points_count,\n",
                "                'Dimension': info.config.params.vectors.size,\n",
                "                'Status': info.status\n",
                "            })\n",
                "        except Exception as e:\n",
                "            print(f'Error: {col.name}: {e}')\n",
                "    \n",
                "    return pd.DataFrame(data)\n",
                "\n",
                "# Get collections\n",
                "df_collections = get_all_collections()\n",
                "\n",
                "if len(df_collections) > 0:\n",
                "    print(f\"\\n{'='*80}\")\n",
                "    print(f\"📊 QDRANT COLLECTIONS ({len(df_collections)} found)\")\n",
                "    print(f\"{'='*80}\\n\")\n",
                "    print(df_collections.to_string(index=False))\n",
                "    \n",
                "    print(f\"\\n{'='*80}\")\n",
                "    print(f\"📈 SUMMARY:\")\n",
                "    print(f\"  Total Collections: {len(df_collections)}\")\n",
                "    print(f\"  Total Embeddings: {df_collections['Embeddings'].sum():,}\")\n",
                "    print(f\"  Unique Datasets: {df_collections['Dataset'].nunique()}\")\n",
                "    print(f\"  Unique Models: {df_collections['Model'].nunique()}\")\n",
                "    print(f\"{'='*80}\")\n",
                "else:\n",
                "    print('⚠️  No collections found in Qdrant')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 3️⃣ Load All Metrics Files"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def load_all_metrics():\n",
                "    '''Load all metric JSON files'''\n",
                "    metrics_files = glob.glob('*metrics*.json')\n",
                "    all_metrics = []\n",
                "    \n",
                "    for file in metrics_files:\n",
                "        try:\n",
                "            with open(file, 'r') as f:\n",
                "                data = json.load(f)\n",
                "                data['metrics_file'] = file\n",
                "                all_metrics.append(data)\n",
                "        except Exception as e:\n",
                "            print(f'Error loading {file}: {e}')\n",
                "    \n",
                "    return pd.DataFrame(all_metrics)\n",
                "\n",
                "df_metrics = load_all_metrics()\n",
                "\n",
                "if len(df_metrics) > 0:\n",
                "    print(f'✅ Loaded {len(df_metrics)} metric files\\n')\n",
                "    \n",
                "    # Show key columns\n",
                "    display_cols = ['collection', 'embeddings_count', 'encoding_inference_time_seconds', \n",
                "                    'indexing_time_seconds', 'embeddings_size_mb', 'metrics_file']\n",
                "    available_cols = [c for c in display_cols if c in df_metrics.columns]\n",
                "    \n",
                "    if available_cols:\n",
                "        print(df_metrics[available_cols].to_string(index=False))\n",
                "else:\n",
                "    print('⚠️  No metrics files found')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 4️⃣ Calculate Efficiency Metrics (for Reviewers)"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def calculate_efficiency_metrics(df):\n",
                "    '''Calculate comprehensive efficiency metrics for reviewer comments'''\n",
                "    if len(df) == 0:\n",
                "        return pd.DataFrame()\n",
                "    \n",
                "    # Ensure we have needed columns\n",
                "    if 'embeddings_count' not in df.columns:\n",
                "        return pd.DataFrame()\n",
                "    \n",
                "    efficiency = df.copy()\n",
                "    \n",
                "    # Encoding efficiency\n",
                "    if 'encoding_inference_time_seconds' in df.columns:\n",
                "        efficiency['encoding_throughput_per_sec'] = (\n",
                "            df['embeddings_count'] / df['encoding_inference_time_seconds']\n",
                "        ).round(2)\n",
                "        efficiency['avg_encoding_time_ms'] = (\n",
                "            (df['encoding_inference_time_seconds'] * 1000) / df['embeddings_count']\n",
                "        ).round(2)\n",
                "    \n",
                "    # Indexing efficiency\n",
                "    if 'indexing_time_seconds' in df.columns:\n",
                "        efficiency['indexing_throughput_per_sec'] = (\n",
                "            df['embeddings_count'] / df['indexing_time_seconds']\n",
                "        ).round(2)\n",
                "        efficiency['avg_indexing_time_ms'] = (\n",
                "            (df['indexing_time_seconds'] * 1000) / df['embeddings_count']\n",
                "        ).round(2)\n",
                "    \n",
                "    # Total processing time\n",
                "    if 'encoding_inference_time_seconds' in df.columns and 'indexing_time_seconds' in df.columns:\n",
                "        efficiency['total_time_seconds'] = (\n",
                "            df['encoding_inference_time_seconds'] + df['indexing_time_seconds']\n",
                "        ).round(2)\n",
                "        efficiency['overall_throughput_per_sec'] = (\n",
                "            df['embeddings_count'] / efficiency['total_time_seconds']\n",
                "        ).round(2)\n",
                "        efficiency['avg_total_time_ms'] = (\n",
                "            (efficiency['total_time_seconds'] * 1000) / df['embeddings_count']\n",
                "        ).round(2)\n",
                "    \n",
                "    # Storage efficiency\n",
                "    if 'embeddings_size_mb' in df.columns:\n",
                "        efficiency['storage_per_1k_embeddings_mb'] = (\n",
                "            (df['embeddings_size_mb'] / df['embeddings_count']) * 1000\n",
                "        ).round(4)\n",
                "        efficiency['storage_per_embedding_kb'] = (\n",
                "            (df['embeddings_size_mb'] * 1024) / df['embeddings_count']\n",
                "        ).round(4)\n",
                "    \n",
                "    # Dimension efficiency\n",
                "    if 'embedding_dimension' in df.columns:\n",
                "        efficiency['bytes_per_dimension'] = (\n",
                "            (df['embeddings_size_mb'] * 1024 * 1024) / (df['embeddings_count'] * df['embedding_dimension'])\n",
                "        ).round(4)\n",
                "    \n",
                "    return efficiency\n",
                "\n",
                "# Calculate efficiency\n",
                "if len(df_metrics) > 0:\n",
                "    df_efficiency = calculate_efficiency_metrics(df_metrics)\n",
                "    \n",
                "    print(f\"\\n{'='*80}\")\n",
                "    print('⚡ EFFICIENCY METRICS (for Reviewer Comments)')\n",
                "    print(f\"{'='*80}\\n\")\n",
                "    \n",
                "    # Show efficiency columns\n",
                "    eff_cols = ['collection', 'embeddings_count', 'encoding_throughput_per_sec', \n",
                "                'indexing_throughput_per_sec', 'overall_throughput_per_sec',\n",
                "                'storage_per_1k_embeddings_mb']\n",
                "    \n",
                "    available_eff_cols = [c for c in eff_cols if c in df_efficiency.columns]\n",
                "    \n",
                "    if available_eff_cols:\n",
                "        print(df_efficiency[available_eff_cols].to_string(index=False))\n",
                "        \n",
                "        # Summary statistics\n",
                "        print(f\"\\n{'='*80}\")\n",
                "        print('📊 EFFICIENCY SUMMARY:')\n",
                "        print(f\"{'='*80}\")\n",
                "        \n",
                "        if 'encoding_throughput_per_sec' in df_efficiency.columns:\n",
                "            print(f\"  Avg Encoding Throughput: {df_efficiency['encoding_throughput_per_sec'].mean():.2f} embeddings/sec\")\n",
                "            print(f\"  Max Encoding Throughput: {df_efficiency['encoding_throughput_per_sec'].max():.2f} embeddings/sec\")\n",
                "        \n",
                "        if 'overall_throughput_per_sec' in df_efficiency.columns:\n",
                "            print(f\"  Avg Overall Throughput: {df_efficiency['overall_throughput_per_sec'].mean():.2f} embeddings/sec\")\n",
                "        \n",
                "        if 'storage_per_1k_embeddings_mb' in df_efficiency.columns:\n",
                "            print(f\"  Avg Storage per 1K embeddings: {df_efficiency['storage_per_1k_embeddings_mb'].mean():.4f} MB\")\n",
                "        \n",
                "        if 'avg_encoding_time_ms' in df_efficiency.columns:\n",
                "            print(f\"  Avg Time per Embedding: {df_efficiency['avg_encoding_time_ms'].mean():.2f} ms\")\n",
                "        \n",
                "        print(f\"{'='*80}\")\n",
                "else:\n",
                "    df_efficiency = pd.DataFrame()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 5️⃣ Detailed Metrics Table"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "if len(df_efficiency) > 0:\n",
                "    print(f\"\\n{'='*80}\")\n",
                "    print('📋 COMPLETE METRICS TABLE')\n",
                "    print(f\"{'='*80}\\n\")\n",
                "    \n",
                "    # Select all relevant columns\n",
                "    detail_cols = ['collection', 'embeddings_count', 'embedding_dimension',\n",
                "                   'encoding_inference_time_seconds', 'indexing_time_seconds', 'total_time_seconds',\n",
                "                   'encoding_throughput_per_sec', 'overall_throughput_per_sec',\n",
                "                   'embeddings_size_mb', 'storage_per_1k_embeddings_mb',\n",
                "                   'avg_encoding_time_ms', 'avg_total_time_ms']\n",
                "    \n",
                "    available_detail_cols = [c for c in detail_cols if c in df_efficiency.columns]\n",
                "    \n",
                "    if available_detail_cols:\n",
                "        display(df_efficiency[available_detail_cols])\n",
                "    else:\n",
                "        display(df_efficiency)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 6️⃣ Performance Visualizations"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "if len(df_efficiency) > 0 and 'encoding_throughput_per_sec' in df_efficiency.columns:\n",
                "    fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n",
                "    \n",
                "    # 1. Throughput comparison\n",
                "    ax = axes[0, 0]\n",
                "    df_efficiency.plot(x='collection', y='overall_throughput_per_sec', kind='barh', \n",
                "                       ax=ax, color='skyblue', legend=False)\n",
                "    ax.set_title('Overall Throughput (embeddings/second)', fontweight='bold', fontsize=12)\n",
                "    ax.set_xlabel('Throughput (embeddings/sec)')\n",
                "    ax.set_ylabel('')\n",
                "    \n",
                "    # 2. Time per embedding\n",
                "    ax = axes[0, 1]\n",
                "    if 'avg_total_time_ms' in df_efficiency.columns:\n",
                "        df_efficiency.plot(x='collection', y='avg_total_time_ms', kind='barh', \n",
                "                           ax=ax, color='coral', legend=False)\n",
                "        ax.set_title('Average Time per Embedding (ms)', fontweight='bold', fontsize=12)\n",
                "        ax.set_xlabel('Time (milliseconds)')\n",
                "        ax.set_ylabel('')\n",
                "    \n",
                "    # 3. Storage efficiency\n",
                "    ax = axes[1, 0]\n",
                "    if 'storage_per_1k_embeddings_mb' in df_efficiency.columns:\n",
                "        df_efficiency.plot(x='collection', y='storage_per_1k_embeddings_mb', kind='barh', \n",
                "                           ax=ax, color='lightgreen', legend=False)\n",
                "        ax.set_title('Storage per 1K Embeddings (MB)', fontweight='bold', fontsize=12)\n",
                "        ax.set_xlabel('Storage (MB)')\n",
                "        ax.set_ylabel('')\n",
                "    \n",
                "    # 4. Embedding count\n",
                "    ax = axes[1, 1]\n",
                "    df_efficiency.plot(x='collection', y='embeddings_count', kind='barh', \n",
                "                       ax=ax, color='plum', legend=False)\n",
                "    ax.set_title('Number of Embeddings Generated', fontweight='bold', fontsize=12)\n",
                "    ax.set_xlabel('Count')\n",
                "    ax.set_ylabel('')\n",
                "    \n",
                "    plt.tight_layout()\n",
                "    plt.show()\n",
                "else:\n",
                "    print('⚠️  Not enough data for visualizations')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 7️⃣ Progress Matrix (Dataset × Model)"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "if len(df_collections) > 0:\n",
                "    # Filter out test collections\n",
                "    df_prod = df_collections[~df_collections['Dataset'].str.contains('test', case=False, na=False)]\n",
                "    \n",
                "    if len(df_prod) > 0:\n",
                "        # Create pivot table\n",
                "        pivot = df_prod.pivot_table(\n",
                "            index='Dataset', \n",
                "            columns='Model', \n",
                "            values='Embeddings', \n",
                "            aggfunc='sum',\n",
                "            fill_value=0\n",
                "        )\n",
                "        \n",
                "        # Create heatmap\n",
                "        plt.figure(figsize=(16, 6))\n",
                "        sns.heatmap(pivot, annot=True, fmt='.0f', cmap='YlGnBu', \n",
                "                    linewidths=0.5, cbar_kws={'label': 'Embeddings Count'})\n",
                "        plt.title('Progress Matrix: Dataset × Model (Embedding Counts)', \n",
                "                  fontsize=14, fontweight='bold', pad=20)\n",
                "        plt.xlabel('Model', fontsize=12)\n",
                "        plt.ylabel('Dataset', fontsize=12)\n",
                "        plt.tight_layout()\n",
                "        plt.show()\n",
                "        \n",
                "        # Calculate completion\n",
                "        total_expected = len(DATASETS) * len(MODELS)\n",
                "        total_completed = len(df_prod)\n",
                "        completion_pct = (total_completed / total_expected) * 100\n",
                "        \n",
                "        print(f\"\\n{'='*80}\")\n",
                "        print(f\"📊 Overall Progress: {total_completed}/{total_expected} ({completion_pct:.1f}%)\")\n",
                "        print(f\"{'='*80}\")\n",
                "    else:\n",
                "        print('Only test collections available. Run full pipeline to see progress matrix.')\n",
                "else:\n",
                "    print('No collections available for progress matrix')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## 8️⃣ Export Efficiency Report"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "if len(df_efficiency) > 0:\n",
                "    # Export to CSV\n",
                "    output_file = f\"efficiency_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv\"\n",
                "    df_efficiency.to_csv(output_file, index=False)\n",
                "    print(f'✅ Efficiency report exported to: {output_file}')\n",
                "    \n",
                "    # Create summary for paper\n",
                "    summary = {\n",
                "        'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),\n",
                "        'total_collections': len(df_efficiency),\n",
                "        'total_embeddings': int(df_efficiency['embeddings_count'].sum()),\n",
                "        'avg_throughput_per_sec': float(df_efficiency['overall_throughput_per_sec'].mean()) if 'overall_throughput_per_sec' in df_efficiency.columns else None,\n",
                "        'avg_storage_per_1k_mb': float(df_efficiency['storage_per_1k_embeddings_mb'].mean()) if 'storage_per_1k_embeddings_mb' in df_efficiency.columns else None,\n",
                "        'avg_time_per_embedding_ms': float(df_efficiency['avg_total_time_ms'].mean()) if 'avg_total_time_ms' in df_efficiency.columns else None\n",
                "    }\n",
                "    \n",
                "    summary_file = f\"efficiency_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json\"\n",
                "    with open(summary_file, 'w') as f:\n",
                "        json.dump(summary, f, indent=2)\n",
                "    \n",
                "    print(f'✅ Summary exported to: {summary_file}')\n",
                "    print(f'\\n📊 Quick Summary:')\n",
                "    print(json.dumps(summary, indent=2))\n",
                "else:\n",
                "    print('No data available for export')"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

# Write the notebook
with open('TABERTA_Results_Dashboard.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("✅ Created TABERTA_Results_Dashboard.ipynb")
